<?php echo $this->renderTabs($this->tabs); ?>
<h3><?php echo pm_Locale::lmsg('quickstartTitle');?></h3>
<p><?php echo pm_Locale::lmsg('quickstartText');?></p>
<ol>
	<li><?php echo pm_Locale::lmsg('step1');?></li>
	<li><?php echo pm_Locale::lmsg('step2');?></li>
	<li><?php echo pm_Locale::lmsg('step3');?></li>
	<li><?php echo pm_Locale::lmsg('step4');?></li>
	<li><?php echo pm_Locale::lmsg('step5');?></li>
	<li><?php echo pm_Locale::lmsg('step6');?></li>
	<li><?php echo pm_Locale::lmsg('step7');?></li>
</ol>
<hr />
<h3><?php echo pm_Locale::lmsg('helpTitle');?></h3>
<h4>- <?php echo pm_Locale::lmsg('moduleHelpTitle');?></h4>
<p><?php echo pm_Locale::lmsg('moduleHelpText');?></p>
<h4>- <?php echo pm_Locale::lmsg('proxySQLHelpTitle');?></h4>
<p><?php echo pm_Locale::lmsg('proxySQLHelpText');?></p>
