#!/bin/bash
mask2cdr ()
{
   # Assumes there's no "255." after a non-255 byte in the mask
   local x=${1##*255.}
   set -- 0^^^128^192^224^240^248^252^254^ $(( (${#1} - ${#x})*2 )) ${x%%.*}
   x=${1%%$3*}
   echo $(( $2 + (${#x}/4) ))
}

case $1 in
-a | --add)
	if [ ! $# -eq 4 ]
	then
			echo "Bad arguments"
			exit 1
	fi

	if [ ! -f /sys/class/net/$2/address ]
	then
			echo "$2 Interface is not found"
			exit 1
	fi
	MAC=`cat /sys/class/net/$2/address`
	NB=`find /etc/systemd/network/ -name "*.network" -exec egrep -l "($2|$MAC)" {} \;|wc -l`
	if [ $NB -lt 2 ]
	then
			if [ $NB -eq 0 ]
			then
					CONFIG="/etc/systemd/network/`ls -1 /etc/systemd/network/|wc -l`-plesk.network"
					echo -e "[Match]\nName=$2\n\n[Link]\nMACAddress=$MAC\n\n[Network]\nDHCP=no" > $CONFIG
			else
					CONFIG=`find /etc/systemd/network/ -name "*.network" -exec egrep -l "($2|$MAC)" {} \;`
			fi
			if [ `cat $CONFIG|grep "Address=$3"|wc -l` -gt 0 ]
			then
					echo "$3 is already configured"
					exit 1
			fi
			echo -e "\n[Address]\nAddress=$3/`mask2cdr $4`" >> $CONFIG
			systemctl restart systemd-networkd
	else
			echo "An error occured, please contact assistance"
			exit 1
	fi
  ;;
-d | --del)
	if [ ! $# -eq 2 ]
	then
			echo "Bad arguments"
			exit 1
	fi

	if [ `find /etc/systemd/network/ -name "*.network" -exec egrep -l "$2" {} \;|wc -l` -eq 1 ]
	then
			CONFIG=`find /etc/systemd/network/ -name "*.network" -exec egrep -l "$2" {} \;`
			if [ `cat $CONFIG|grep "Address=$2"|wc -l` -eq 0 ]
			then
					echo "IP $2 not found"
					exit 1
			fi
			cat $CONFIG|tr '\n' '@'|sed -e "s/@@\[Address\]@Address=$2\(\/[0-9]\+\)\?//g"|tr '@' '\n' > /tmp/config && rm -f $CONFIG && mv /tmp/config $CONFIG
			systemctl restart systemd-networkd
	else
			echo "An error occured, please contact assistance"
			exit 1
	fi
	;;
*)
	plesk sbin ifmng-orig $*
	;;
esac
exit $?

